# Generated by Django 3.1.14 on 2022-09-30 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.AutoField(help_text='Unique Id to identify a user', primary_key=True, serialize=False)),
                ('user_name', models.CharField(help_text='Name of the user', max_length=255)),
                ('password', models.CharField(help_text='User Password', max_length=55)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Created at datetime')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Updated at datetime')),
            ],
            options={
                'db_table': 'user_details',
            },
        ),
    ]
