# Generated by Django 3.1.14 on 2022-09-30 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentDetails',
            fields=[
                ('id', models.AutoField(help_text='Unique ID', primary_key=True, serialize=False)),
                ('gender', models.CharField(help_text='Gender of the Student', max_length=10)),
                ('race', models.CharField(help_text='Race/ethnicity of the student', max_length=50)),
                ('parent_education', models.CharField(help_text='Parent Education Level of the student', max_length=50)),
                ('lunch', models.CharField(help_text='Lunch', max_length=255)),
                ('test_preparation_course', models.CharField(help_text='Test Preparation course', max_length=255)),
                ('math_score', models.IntegerField(help_text='Math Score')),
                ('reading_score', models.IntegerField(help_text='Reading Score')),
                ('writing_score', models.IntegerField(help_text='Writing Score')),
            ],
            options={
                'db_table': 'student_details',
            },
        ),
    ]
